SELECT* from(
select PIPE_TEHNOLOG_REGIM."ID простого участка",PIPE_TEHNOLOG_REGIM."Дата расчета" ,PIPE_TEHNOLOG_REGIM."Обводненность"
FROM PIPE_TEHNOLOG_REGIM
WHERE PIPE_TEHNOLOG_REGIM."ID простого участка"={ID}
UNION ALL
select PIPE_TEHNOLOG_REGIM_OLD."ID простого участка",PIPE_TEHNOLOG_REGIM_OLD."Дата расчета" ,PIPE_TEHNOLOG_REGIM_OLD."Обводненность"
FROM PIPE_TEHNOLOG_REGIM_OLD
WHERE PIPE_TEHNOLOG_REGIM_OLD."ID простого участка"={ID})